# Generated by Django 6.0.1 on 2026-01-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_type', models.CharField(blank=True, choices=[('phone', 'Phone'), ('technical', 'Technical'), ('onsite', 'Onsite'), ('hr', 'HR'), ('other', 'Other')], max_length=20, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='companies.company')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
