# Generated by Django 6.0.1 on 2026-01-13 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_remove_interviewevent_end_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewevent',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewevent',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('technical', 'Technical'), ('onsite', 'Onsite'), ('online', 'Online'), ('hr', 'HR'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
